apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: azilehub-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.232.60-192.168.232.70

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: azilehub-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - azilehub-pool
