apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azilehub-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/zainul1114/azilehub-k8s-phase1.git
    targetRevision: main
    path: k8s/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: azilehub

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
