apiVersion: v1
kind: ConfigMap
metadata:
  name: azilehub-config
  namespace: azilehub

data:
  ENVIRONMENT: "production"
  CONTENT_SERVICE_URL: "http://content-service:8000"
  CONTACT_SERVICE_URL: "http://contact-service:8000"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "azilehub"
