apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: azilehub

spec:

  scaleTargetRef:

    apiVersion: apps/v1
    kind: Deployment
    name: frontend

  minReplicas: 2
  maxReplicas: 5

  behavior:

    scaleUp:

      stabilizationWindowSeconds: 0

      policies:

        - type: Percent
          value: 100
          periodSeconds: 60

    scaleDown:

      stabilizationWindowSeconds: 300

      policies:

        - type: Percent
          value: 50
          periodSeconds: 60

  metrics:

    - type: Resource

      resource:

        name: cpu

        target:

          type: Utilization
          averageUtilization: 70

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: content-service-hpa
  namespace: azilehub

spec:

  scaleTargetRef:

    apiVersion: apps/v1
    kind: Deployment
    name: content-service

  minReplicas: 2
  maxReplicas: 5

  metrics:

    - type: Resource

      resource:

        name: cpu

        target:

          type: Utilization
          averageUtilization: 70

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: contact-service-hpa
  namespace: azilehub

spec:

  scaleTargetRef:

    apiVersion: apps/v1
    kind: Deployment
    name: contact-service

  minReplicas: 2
  maxReplicas: 5

  metrics:

    - type: Resource

      resource:

        name: cpu

        target:

          type: Utilization
          averageUtilization: 70
