apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: azilehub

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - content-service.yaml
  - contact-service.yaml
  - frontend.yaml
  - services.yaml
  - networkpolicy.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml
