apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: azilehub

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

  - target:
      kind: Deployment
      name: content-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: contact-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
